package store.utils;

import store.model.Product;

import java.util.List;
import java.util.stream.Collectors;

public class ProductsManager {



    public static List<Product> getListOfProductsWhichHasOffer(List<Product> list){

        return  list.stream().filter( e -> e.hasOffer()).collect(Collectors.toList());

    }

    public static List<Product> getListOfProducts(String category){

        List<Product> list = getListOfProducts();
        return  list.stream().filter( e -> CategoryManager.isUnderCategory(e.getCategory(),category)).collect(Collectors.toList());

    }
    public static List<Product> getListOfProducts(){
        return List.of(

                new Product("Asus Portable X543N"," Le ASUS X543 intègre un processeur Intel avec 4 Go de mémoire pour des performances à la fois rapides et fluides. Il offre également une capacité de stockage de son disque dur grande capacité. Il est l'ordinateur portable parfait pour vos divertissements et tâches professionnelles.", "Pc Portable", 1015.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/69/3863/1.jpg?5528", 18),
                new Product("Asus Pc E410MA"," Avec l'ASUS E410 compact et léger, la productivité est toujours à portée de main. Il se glisse facilement dans votre sac à dos ou votre petit sac pour que vous puissiez faire vos devoirs ou créer du contenu où que vous soyez.", "Pc Portable", 729.9f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/10/4883/1.jpg?5804"),
                new Product("LENOVO IDEAPAD ","L'ordinateur portable Ideapad C340-14IWL de Lenovo a été spécialement conçu pour vous offrir un usage informatique simplifié, en toutes circonstances. Performant, il est doté d'un écran LED tactile 14\" Full HD, d'un processeur AMD Ryzen 3, d'une carte graphique AMD Radeon vega 3", "UltraBook", 1699.9f,"https://mk-media.mytek.tn/media/catalog/product/cache/8be3f98b14227a82112b46963246dfe1/a/s/asusss_46.jpg"),
                new Product("LENOVO IDEAPAD C340"," L'ordinateur portable Ideapad C340-14IWL de Lenovo a été spécialement conçu pour vous offrir un usage informatique simplifié, en toutes circonstances. Performant, il est doté d'un écran LED tactile 14\" Full HD, d'un processeur AMD Ryzen 3, d'une carte graphique AMD Radeon vega 3", "UltraBook", 1789.9f,"https://mk-media.mytek.tn/media/catalog/product/cache/8be3f98b14227a82112b46963246dfe1/l/e/lenpen.jpg", 30),
                new Product("Apple MacBook Air","Le MacBook Air, le plus fin et léger des portables Apple, est métamorphosé par la puissante puce Apple M1. Avec un gain de performances spectaculaire pour le CPU et le GPU. Et jusqu’à 18 heures d’autonomie. Travaillez plus vite que jamais grâce au processeur central 8 cœurs ultra-rapide. Passez au niveau supérieur dans les jeux et les apps aux graphismes sophistiqués grâce à un GPU intégrant jusqu’à 8 cœurs. Accélérez les tâches d’apprentissage automatique, avec le Neural Engine 16 cœurs. Et profitez d’une autonomie record pouvant atteindre 18 heures et d’un design silencieux, sans ventilateur. Le MacBook Air est encore plus puissant.", "Mac", 4015.9f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/95/2753/1.jpg?7965", 3),
                new Product("Apple MacBook Air 13 pouces M1","Le MacBook Air, le plus fin et léger des portables Apple, est métamorphosé par la puissante puce Apple M1. Avec un gain de performances spectaculaire pour le CPU et le GPU. Et jusqu’à 18 heures d’autonomie. Travaillez plus vite que jamais grâce au processeur central 8 cœurs ultra-rapide. Passez au niveau supérieur dans les jeux et les apps aux graphismes sophistiqués grâce à un GPU intégrant jusqu’à 8 cœurs. Accélérez les tâches d’apprentissage automatique, avec le Neural Engine 16 cœurs. Et profitez d’une autonomie record pouvant atteindre 18 heures et d’un design silencieux, sans ventilateur. Le MacBook Air est encore plus puissant.", "Mac", 4990.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/83/8653/1.jpg?2444"),
                new Product("WHITELEAD T-shirt-Attack-On-Titan"," T-Shirt straight de couleur Noir 100% coton ajustés et confortables pour tous les jours et les soirées d'été  car il peut être associé à un bermuda, un Jean, un chino... Comme il vous plaira.Ce T-Shirt possède un imprimé sur l'avant (Attack On Titan) peut-être porté tout seul ou  sous une chemise ouverte pour un look casual chic et élégant.", "T-shirts, Polo, Chemises", 39.9f,"https://tn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/93/4782/1.jpg?8724", 30),
                new Product("Pack - 3 T-shirt","Des t-shirts sur n'en a jamais assez. Optez pour ce pack de 3 t-shirts aux couleurs basiques (noir, blanc et gris) et variez les looks.", "T-shirts, Polo, Chemises", 26.9f,"https://tn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/94/8272/1.jpg?8846"),
                new Product("Sweat à capuche - Rouge"," Sweat à Capuche de  couleur ROUGE  Unis pour Homme à manches longues avec une pochette en avant", "Pulls, Gilets", 12.5f,"https://tn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/72/2663/1.jpg?7148", 30),
                new Product("Pull Noir La Casa De Papel"," Pull  de couleur  Noir à manches longues.Les pulls sont parfaits pour un look urbain .Ce pull se porte  avec un jeans, un Jogging ou bien un short.Composition :  coton.Ce Pull possède un imprimé sur l'avant (la casa de papel)", "Pulls, Gilets", 27.9f,"https://tn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/95/5203/1.jpg?8267"),
                new Product("Robe soirée - Spandex - Noir"," Robe de soirée courte, ornée d'une bande transparente noire au niveau de la taille.", "Robes", 79.9f,"https://www.savanna.tn/30316-home_default/robe-soiree-spandex-noir.jpg", 30),
                new Product("Robe - Lila Tounsia - Noire"," Robe traditionnelle  noire en fibranne et dentelle avec une billet arabesque en couleur fluo multicouleur (jaune , vert ,...) inspiré par la culture Amazighe berbère", "Robes", 33.0f,"https://tn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/51/6262/1.jpg?0567"),
                new Product("Combinaison bretelles - imprimé"," Cette combinaison à fines bretelles est indispensable, cette saison, pour suivre la mode ethnique. Combinaison avec doubles bretelles, grande ouverture et large pantalon. la combinaison est totalement imprimée.", "Ensembles & Combinaisons", 55.0f,"https://tn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/15/8752/1.jpg?9049", 30),
                new Product("Salopette Jeans Délavée"," Coup de cœur pour cette salopette pantalon délavée brodée et un peu déchirée au niveau des jambes,l’ouverture boutonnée sur les côtés, les deux poches arrière au niveau du pantalon, poche plaquée poitrine l’embellit, les passants pour ceinture et les deux poches devant au niveau du pantalon.", "Ensembles & Combinaisons", 63.9f,"https://tn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/71/5742/1.jpg?6822"),
                new Product("Diadora Chaussure"," Baskets basses unisexes pour enfant avec détails ajourés, fermeture velcro pratique, fregio, languette et arrière assortis.", "Chaussures", 98.0f,"https://tn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/57/0243/1.jpg?7359", 30),
                new Product("Gioseppo Chaussures"," chic et élégance garantis. Pointures de 20 à 31.Marque Gioseppo.Des classiques qui ne se démodent jamais.", "Chaussures", 59.95f,"https://tn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/62/5743/1.jpg?6726"),
                new Product("Hummel T-SHIRT"," Gardant sa douceur et sa simplicité, le T-SHIRT hmlTRES S / S a un logo hummel® imprimé sur le devant et un col ras du cou côtelé.", "Vetements", 35.0f,"https://tn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/85/3262/1.jpg?3317", 30),
                new Product("Lc Waikiki Manteau pour Garçons"," LC Waikiki vise à s'assurer que des produits sûrs qui conviennent aux styles et aux budgets des consommateurs et qui ne nuisent pas à la santé humaine et à l'environnement sont fabriqués et proposés sur le marché conformément aux besoins et aux attentes des consommateurs à la qualité souhaitée et dans les délais.", "Vetements", 39.9f,"https://tn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/36/2883/1.jpg?4486"),
                new Product("Micro Onde - 20 Litres - Noir"," Un four à micro-onde ou plus simplement un micro-ondes ou même un microonde est un appareil électroménager utilisé principalement pour le chauffage et la cuisson rapide d'aliments, par l'agitation des molécules d'eau qu'ils contiennent, sous l'effet d'un rayonnement micro-onde.", "Micro-ondes", 199.0f,"https://tn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/75/4973/1.jpg?9843", 30),
                new Product("STAR ONE Micro Onde - 20 Litres - Silver"," Un four à micro-onde ou plus simplement un micro-ondes ou même un microonde est un appareil électroménager utilisé principalement pour le chauffage et la cuisson rapide d'aliments, par l'agitation des molécules d'eau qu'ils contiennent, sous l'effet d'un rayonnement micro-onde.", "Micro-ondes", 209.0f,"https://tn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/70/8823/1.jpg?2041"),
                new Product("Moulinex Mixeur plongeant"," Pour vos soupes, vos glaces et vos sauces maison, vous voulez un mixer plongeant efficace, n'hésitez pas à découvrir ce Mixeur plongeant OptiChef.Doté d'un design moderne pour de très bons résultats de mélange, ce mixeur d'une puissance de 350 W avec vitesse vous facilitera la tâche dans votre cuisine au quotidien, son pied en métal amovible et son bec verseur de 0,8L , ce mixeur plongeant OptiChef n'a rien à envier au autres bras mixeurs.Achetez le sur Jumia Tunisie et recevez le chez vous dans les plus brefs délais.", "Mixeurs & Blenders", 79.0f,"https://tn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/84/5313/1.jpg?0565", 30),
                new Product("Moulinex Blender Genuine"," e blender d'une puissance de 400 W est doté d'un système Air Cooling innovant qui optimise le flux d'air autour du moteur afin d’accroître sa durée de vie et éviter une éventuelle surchauffe pour jusqu’à 3 minutes de mixage continu.", "Mixeurs & Blenders", 137.0f,"https://tn.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/95/0601/1.jpg?9844"),
                new Product("Tefal Set deux poêles"," 100 % FACILE A NETTOYER: gamme revêtue à l'intérieur et à l'extérieur pour un nettoyage ultra simple et facile à utiliser même pour les cuisiniers débutantsRevêtement TITANIUM PRO dure jusqu'à 2 fois plus longtemps que le revêtement TITANIUM FORCE", "Casseroles & Poeles", 159.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/81/7673/1.jpg?7844", 38),
                new Product("Big Chief Couscoussier"," Le couscoussier est l’ustensile qui va faire toute la différence.La vapeur de cuisson est chargée des arômes de la viande et des légumes et la semoule se parfume avec délicatesse avec un couscoussier.", "Casseroles & Poeles", 39.9f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/01/2251/1.jpg?4486",11),
                new Product("Fouet Pâtissier en Plastique"," Ce fouet est tendance grâce à son design et à sa praticité. En effet, il est rétractable. Il suffit de bouger la bague qui se trouve sur son manche pour le rétracter et gagner de la place en le rangeant.", "Accessoires et ustensiles", 15.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/32/8342/1.jpg?4126", 16),
                new Product("Tapis de Cuisson en Silicone"," Peut être utilisé comme un isolant thermique, anti-brûlure, et protège le bureau. Peut être utilisé pour faire du chocolat, pudding, biscuits, gâteaux, glaçons, polyvalent et amusant.", "Accessoires et ustensiles", 25.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/72/6352/1.jpg?7068", 24),
                new Product("Table De Coin - Crème","En bois MDF écologique, il n’est pas nocif pour la santé des humains. Grâce à sa surface lisse, vous pouvez facilement nettoyer la table de coin GIEX avec un chiffon de nettoyage. La table de coin  est dotée d’une surface lisse, d’une belle apparence, de performances durables et de caractéristiques de protection de l’environnement. ", "Meubles", 22.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/07/7802/1.jpg?8704"),
                new Product("Pouf Coffre de Rangement"," Belle pouf avec une forme ronde. L'avantage de son apparence est de courtepointe avec des boutons qui ont été utilisés sur le siège. Il peut être utilisé comme un rangement pratique, un endroit supplémentaire pour s'asseoir ou un élément décoratif de la pièce.", "Meubles", 170.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/51/8371/1.jpg?6613", 40),
                new Product("Étagère Murale Suspendue"," Ces étagères murale suspendue  en bois sont exactement ce dont vous avez besoin si vous êtes à la recherche de cette touche parfaite de décor minimaliste.", "Décoration de maison", 55.9f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/14/7832/1.jpg?0924", 60),
                new Product("Lampe décorative 3d"," Vous pouvez utiliser la lampe LED, qui est un produit très élégant et décoratif conçu en forme d'ananas, sur la table, sur le mur, dans vos cadres de souvenirs, comme veilleuse dans vos enfants ou dans votre chambre.", "Décoration de maison", 65.5f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/01/4753/1.jpg?4691", 50),
                new Product("Sotufab Table pliante - Blanc","La table de jardin Holidays est polyvalente, peu encombrante et facile à transporter. En résine de synthèse, cette table résistera au temps, aux UV ainsi qu'aux intempéries. 2 configurations sont possible pour accueillir jusqu'à 4 personnes.", "Tables d'extérieur", 199.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/13/8913/1.jpg?4823", 33),
                new Product("Sotufab Table - Blanc","TABLE RENO (J) BLANC AZURE est polyvalente, peu encombrante et facile à transporter. En résine de synthèse, cette table résistera au temps, aux UV ainsi qu'aux intempéries.", "Tables d'extérieur", 59.9f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/97/5903/1.jpg?1348"),
                new Product("Sotufab lot de deux Chaises Pliable Ruspina - Blanc"," Chaise pliable Ruspina Légère et facile à ranger, cette Chaise de jardin est aussi pliante pour un rangement facilité hors saison, leur revêtement anti-dérapant leur système ingénieux de loquet de haute qualité en  plastique robuste et antidérapant idéale pour les jardins ,maisons plage... Ces chaise de jardin pliante est simple et facile à utiliser ,facilement transportables ,Ce chaise pliante  conçue pour un usage intérieur et extérieur qui sont les accessoires indispensables pour vous, elle seront appréciées de tous les invités", "Chaises d'extérieur", 65.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/04/3482/1.jpg?1805"),
                new Product("Sotufab Lot de 4 chaises - Plastique"," La chaise est un siège sans bras ou accotoir , à une place et muni d'un dossier, d'une assise et d'un piétement généralement à quatre pieds. Ce meuble tient une place importante dans l'histoire du mobilier français et du design", "Chaises d'extérieur", 85f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/16/0681/1.jpg?5812"),
                new Product("Tuyau d' arrosage- Magic hose - Vert"," Découvrez le tuyau d'arrosage rétractable révolutionnaire ! Grâce à sa composition innovante en latex, ce tuyau d'arrosage est extensible, puis se rétracte après son utilisation. Avec la pression de l'eau, le tuyau s'agrandit en longueur pour atteindre jusqu'à 3 fois sa taille d'origine ! 37.5 Mètres lorsque vous branchez le tuyau d'arrosage à votre robinet extérieur et ouvrez l'arrivée d'eau.Lorsque vous avez terminé d'utiliser le tuyau, il vous suffit de couper l'arrivée d'eau et il se rétracte pour reprendre sa taille normale. Fini les n uds et les problèmes de stockage avec votre tuyau d arrosage ! ", "Outillage de jardin", 48.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/74/8213/1.jpg?6356", 25),
                new Product("Arroseur a piquet - Rotatif pour arrosage gazon"," Fabriqué en matériau ABS respectueux de l'environnement, ce qui garantit une utilisation robuste et constante, des performances stables et une longue durée de vie.Action rotative à 360 degrés sans autre équipement d'alimentation auxiliaire juste par la pression d'alimentation en eau domestique.", "Outillage de jardin", 15.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/09/6413/1.jpg?5105", 23),
                new Product("Intex Piscine familiale"," PISCINE GONFLABLE FACILE À INSTALLER (10 PI X 30 POUCES) - La piscine pour la meilleure heure d'été rend votre été plus amusant et agréable Facile à assembler Aide à renforcer l'esprit de compétition entre les membres de la famille Taille: 16ft X 8ft X 42in Prism Frame Pool Set Âge recommandé 12 ans et plus", "Piscines", 570.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/54/7852/1.jpg?3416", 26),
                new Product("Intex Fauteuil gonflable"," Nos fauteuils inclinables gonflables sont faciles à utiliser, pliables, portables et faciles à ranger. Ils sont donc largement utilisés pour les pauses déjeuner, les activités en plein air, la pêche, les jardins, etc.", "Piscines", 199.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/27/4652/1.jpg?0076", 20),
                new Product("Barbecue à Charbon - Rond"," BBQ Barbecue 18.5' en acier inoxydable avec thermomètre - Charbon de BoisNotre barbecue au charbon de bois polyvalent est un incontournable pour tous les adeptes du barbecue, il offre de nombreuses options tels que poissons, viandes, légumes ou volaille, ce barbecue performant vous offrira de somptueux repas.", "Barbecues à charbon", 699.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/53/7152/1.jpg?3203", 29),
                new Product("Barbecue à Charbon Rond en acier inoxydable","BBQ Barbecue 18.5\" en acier inoxydable avec thermomètre - Charbon de BoisNotre barbecue au charbon de bois polyvalent est un incontournable pour tous les adeptes du barbecue, il offre de nombreuses options tels que poissons, viandes, légumes ou volaille, ce barbecue performant vous offrira de somptueux repas.", "Barbecues à charbon", 710.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/00/6183/1.jpg?3869", 30),
                new Product("Livoo Plancha Gril Électrique"," Bénéficiez des bienfaits d’une cuisson saine en vous procurant la plancha proposée à prix réduit chez Jumia. Il vous suffit de choisir la plancha répondant à vos attentes. Les planchas commercialisées à des tarifs très attractifs.", "Barbecues électriques", 130.0f, "https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/17/8483/1.jpg?8004"),
                new Product("Barbecue Electrique - Noir","Ayant débuté son activité dans le secteur de l’électroménager à Istanbul en 2001. Akel, continue à développer son portefeuille de produits avec une nouvelle vision, cette dernière a réussi à incorporer de nouveaux produits et de nouveaux modèles dans son catalogue chaque année.", "Barbecues électriques", 99.0f,"https://tn.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/31/7722/1.jpg?5870", 24)

                );
    }


}